/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newpos_uart_SerialPort */

#ifndef _Included_com_newpos_uart_SerialPort
#define _Included_com_newpos_uart_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef com_newpos_uart_SerialPort_PORT_6210LINK8210
#define com_newpos_uart_SerialPort_PORT_6210LINK8210 7L
/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    open
 * Signature: (ILjava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_newpos_uart_SerialPort_open
(JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_newpos_uart_SerialPort_close
(JNIEnv *, jclass);

/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    sysBeep
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_newpos_uart_SerialPort_sysBeep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    injectKey
 * Signature: (IIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_newpos_uart_SerialPort_injectKey
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray);
  

/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    writeKeyUnified
 * Signature: (IIIIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_newpos_uart_SerialPort_writeKeyUnified
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jbyteArray);  

  
/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    vendorGet
 * Signature: ([B[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_newpos_uart_SerialPort_vendorGet
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jintArray);
  
/*
 * Class:     com_newpos_uart_SerialPort
 * Method:    checkKeyUnified
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_newpos_uart_SerialPort_checkKeyUnified
  (JNIEnv *, jclass, jint, jint, jint);  
  
#ifdef __cplusplus
}
#endif
#endif
